
// AUTH

export const AUTH_LOGIN_PENDING = 'AUTH_LOGIN_PENDING';
export const AUTH_LOGIN_FULFILLED = 'AUTH_LOGIN_FULFILLED';
export const AUTH_LOGIN_REJECTED = 'AUTH_LOGIN_REJECTED';

export const AUTH_SEND_TOKEN_PENDING = 'AUTH_SEND_TOKEN_PENDING';
export const AUTH_SEND_TOKEN_FULFILLED = 'AUTH_SEND_TOKEN_FULFILLED';
export const AUTH_SEND_TOKEN_REJECTED = 'AUTH_SEND_TOKEN_REJECTED';

export const AUTH_LOGOUT_PENDING = 'AUTH_LOGOUT_PENDING';
export const AUTH_LOGOUT_FULFILLED = 'AUTH_LOGOUT_FULFILLED';
export const AUTH_LOGOUT_REJECTED = 'AUTH_LOGOUT_REJECTED';

export const AUTH_UPDATE_PENDING = 'AUTH_UPDATE_PENDING';
export const AUTH_UPDATE_FULFILLED = 'AUTH_UPDATE_FULFILLED';
export const AUTH_UPDATE_REJECTED = 'AUTH_UPDATE_REJECTED';

// EVENT

export const EVENT_CREATE_PENDING = 'EVENT_CREATE_PENDING';
export const EVENT_CREATE_FULFILLED = 'EVENT_CREATE_FULFILLED';
export const EVENT_CREATE_REJECTED = 'EVENT_CREATE_REJECTED';

export const EVENT_FETCH_PENDING = 'EVENT_FETCH_PENDING';
export const EVENT_FETCH_FULFILLED = 'EVENT_FETCH_FULFILLED';
export const EVENT_FETCH_REJECTED = 'EVENT_FETCH_REJECTED';

// COMMON
export const LOCAL_STORAGE_AUTH_TOKEN = 'auth_token';
