export const EVENT_CREATE_PENDING = 'EVENT_CREATE_PENDING';
export const EVENT_CREATE_FULFILLED = 'EVENT_CREATE_FULFILLED';
export const EVENT_CREATE_REJECTED = 'EVENT_CREATE_REJECTED';

export const EVENT_FETCH_PENDING = 'EVENT_FETCH_PENDING';
export const EVENT_FETCH_FULFILLED = 'EVENT_FETCH_FULFILLED';
export const EVENT_FETCH_REJECTED = 'EVENT_FETCH_REJECTED';
